# robot position controller parameters

ur5_shoulder_pan_joint_position_controller:
  type: velocity_controllers/JointPositionController
  joint: $(arg prefix)ur5_shoulder_pan_joint
  pid: {p: &p_gain 10.0, i: &i_gain 0.0, d: &d_gain 0.0,
        i_clamp_min: &i_min 0.0, i_clamp_max: &i_max 0.0, antiwindup: &awup false}

ur5_shoulder_lift_joint_position_controller:
  type: velocity_controllers/JointPositionController
  joint: $(arg prefix)ur5_shoulder_lift_joint
  pid: {p: *p_gain, i: *i_gain, d: *d_gain,
            i_clamp_min: *i_min, i_clamp_max: *i_max, antiwindup: *awup}

ur5_elbow_joint_position_controller:
  type: velocity_controllers/JointPositionController
  joint: $(arg prefix)ur5_elbow_joint
  pid: {p: *p_gain, i: *i_gain, d: *d_gain,
        i_clamp_min: *i_min, i_clamp_max: *i_max, antiwindup: *awup}

ur5_wrist_1_joint_position_controller:
  type: velocity_controllers/JointPositionController
  joint: $(arg prefix)ur5_wrist_1_joint
  pid: {p: *p_gain, i: *i_gain, d: *d_gain,
        i_clamp_min: *i_min, i_clamp_max: *i_max, antiwindup: *awup}

ur5_wrist_2_joint_position_controller:
  type: velocity_controllers/JointPositionController
  joint: $(arg prefix)ur5_wrist_2_joint
  pid: {p: *p_gain, i: *i_gain, d: *d_gain,
        i_clamp_min: *i_min, i_clamp_max: *i_max, antiwindup: *awup}

ur5_wrist_3_joint_position_controller:
  type: velocity_controllers/JointPositionController
  joint: $(arg prefix)ur5_wrist_3_joint
  pid: {p: *p_gain, i: *i_gain, d: *d_gain,
        i_clamp_min: *i_min, i_clamp_max: *i_max, antiwindup: *awup}
